unique1: unique.c unsorted.c
	gcc -o unique1 unique.c unsorted.c
	time ./unique1 /scratch/coen12/Bible.txt
	time ./unique1 /scratch/coen12/Genesis.txt
	time ./unique1 /scratch/coen12/GreenEggsAndHam.txt
	time ./unique1 /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./unique1 /scratch/coen12/Macbeth.txt
	time ./unique1 /scratch/coen12/TheCountOfMonteCristo.txt
	time ./unique1 /scratch/coen12/TheSecretGarden.txt
	time ./unique1 /scratch/coen12/TheWarOfTheWorlds.txt
	time ./unique1 /scratch/coen12/TreasureIsland.txt
	time ./unique1 /scratch/coen12/TwentyThousandLeagues.txt

parity1: parity.c unsorted.c
	gcc -o parity1 parity.c unsorted.c
	time ./parity1 /scratch/coen12/Bible.txt
	time ./parity1 /scratch/coen12/Genesis.txt
	time ./parity1 /scratch/coen12/GreenEggsAndHam.txt
	time ./parity1 /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./parity1 /scratch/coen12/Macbeth.txt
	time ./parity1 /scratch/coen12/TheCountOfMonteCristo.txt
	time ./parity1 /scratch/coen12/TheSecretGarden.txt
	time ./parity1 /scratch/coen12/TheWarOfTheWorlds.txt
	time ./parity1 /scratch/coen12/TreasureIsland.txt
	time ./parity1 /scratch/coen12/TwentyThousandLeagues.txt

unique2: unique.c sorted.c
	gcc -o unique2 unique.c sorted.c
	time ./unique2 /scratch/coen12/Bible.txt
	time ./unique2 /scratch/coen12/Genesis.txt
	time ./unique2 /scratch/coen12/GreenEggsAndHam.txt
	time ./unique2 /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./unique2 /scratch/coen12/Macbeth.txt
	time ./unique2 /scratch/coen12/TheCountOfMonteCristo.txt
	time ./unique2 /scratch/coen12/TheSecretGarden.txt
	time ./unique2 /scratch/coen12/TheWarOfTheWorlds.txt
	time ./unique2 /scratch/coen12/TreasureIsland.txt
	time ./unique2 /scratch/coen12/TwentyThousandLeagues.txt

parity2: parity.c sorted.c
	gcc -o parity2 parity.c sorted.c
	time ./parity2 /scratch/coen12/Bible.txt
	time ./parity2 /scratch/coen12/Genesis.txt
	time ./parity2 /scratch/coen12/GreenEggsAndHam.txt
	time ./parity2 /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./parity2 /scratch/coen12/Macbeth.txt
	time ./parity2 /scratch/coen12/TheCountOfMonteCristo.txt
	time ./parity2 /scratch/coen12/TheSecretGarden.txt
	time ./parity2 /scratch/coen12/TheWarOfTheWorlds.txt
	time ./parity2 /scratch/coen12/TreasureIsland.txt
	time ./parity2 /scratch/coen12/TwentyThousandLeagues.txt
